kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-db
  template:
    metadata:
      labels:
        app: demo-db
    spec:
      containers:
      - name: users
        image: fbereche/demo-db:1.0.0
        ports:
        - containerPort: 3306
